Unit testing and audio playback
LukaszTheLittle/BeatBox pull request #2
Opened 2022-06-06 22:33 UTC by LukaszTheLittle

Added functionality of playing all of the .wav files. 
Wrote unit tests for `SoundViewModel` integration with `BeatBox`.

2022-06-07 08:22 UTC, Pantkowsky requested changes

2022-06-07 08:22 UTC, Pantkowsky commented on app/src/main/java/com/bignerdranch/android/beatbox/MainActivity.kt
> +            binding.viewModel = SoundViewModel(beatBox)
is `beatBox` here a global variable of `MainActivity` ? If yes, then it would be better if you passed it as an argument to the `SoundHolder` instead of referencing it as a global variable and using it as an arg to `SoundViewModel`. When creating `private inner class` (but generally, when passing arguments around), consider how much work will you have when you need to refactor it, by for example moving it to separate file. If `SoundHolder` accepted `beatBox` as an argument, you would have much less refactoring then, and the code would be cleaner. Remember the topic of _side effects_ ?

2022-06-07 22:01 UTC, LukaszTheLittle commented on app/src/main/java/com/bignerdranch/android/beatbox/MainActivity.kt
> +            binding.viewModel = SoundViewModel(beatBox)
You have a good point. I removed global variable as you advised and passed it as an argument wherever it was needed.

2022-06-12 20:29 UTC, Pantkowsky approved these changes

2022-06-13 18:11 UTC, merged